fmovies/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('scraper.urls', namespace = 'scraper')),
]

scraper/urls.py
#Url Conf
#Namespace: scraper
from django.conf.urls import url
from scraper.views import Index, Scraper, Add_Series, Tracker, Delete_Series, \
                          Update_Series, Search_Series, Latest_Movies

urlpatterns = [
    url(r'^$', Index.as_view(), name = 'index'),

    url(r'^scrape/$', Scraper.as_view(), name = 'scrape'),
    url(r'^scrape/add/$', Add_Series.as_view(), name = 'add_series'),

    url(r'^tracker/$', Tracker.as_view(), name = 'tracker'),
    url(r'^tracker/search/$', Search_Series.as_view(), name = 'search'),
    url(r'^tracker/remove/(?P<pk>[0-9]+)/$', Delete_Series.as_view(), name = 'remove_series'),
    url(r'^tracker/update/(?P<pk>[0-9]+)/$', Update_Series.as_view(), name = 'update_series'),

    url(r'^latest_movies/$', Latest_Movies.as_view(), name = 'latest_movies'),
]

scraper/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Serie(models.Model):
    name = models.CharField(max_length=40)
    episode_link = models.CharField(max_length=300, null = True, blank = True)
    episode_num = models.IntegerField(null = True, blank = True)
    season = models.IntegerField()
    last_updated = models.DateTimeField(auto_now = True)

    def get_absolute_url(self):
        return reverse('scraper:tracker')

scraper/views.py
from bs4 import BeautifulSoup
import time
import requests
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.views import View
from django.views.generic.edit import CreateView, DeleteView
from scraper.models import Serie

BASE_URL = "http://fmovies.to"

class Index(View):
    def get(self, request):
        return render(request, 'index.html')

# Display the list of tracked series with their stored info.
class Tracker(View):
    def get(self, request):
        series = Serie.objects.all().order_by('name')
        return render(request, 'tracker.html', {'cont': series})

class Add_Series(CreateView):
    model = Serie
    fields = ['name', 'season']

    def form_valid(self, form):
        self.object = form.save(commit = False)
        # Format spaces with '+'.
        s_name = form.cleaned_data["name"].replace(' ', '+') + '+' + str(form.cleaned_data["season"])
        s_name = s_name.replace('+1', '') if s_name.endswith('+1') else s_name
        # Get info for new Entry and scrape required info.
        ep = get_last_ep(s_name)
        self.object.episode_link = ep["episode_link"]
        self.object.episode_num = ep["episode_num"]
        self.object.save()
        return super().form_valid(form)

# Change to use Ajax so page isn't refreshed and update DOM with jQuery.
class Update_Series(View):
    def post(self, request, pk):
        t = Serie.objects.get(pk = pk)
        name = (str(t.name) + ' ' + str(t.season)).replace(' ', '+')
        dt = get_last_ep(name)
        t.episode_link = dt["episode_link"]
        t.episode_num = dt["episode_num"]
        t.save()
        return redirect('scraper:tracker')

# Change to use Ajax so page isn't refreshed and update Dom with jQuery.
class Delete_Series(DeleteView):
    model = Serie
    def get_success_url(self):
        return reverse('scraper:tracker')

# AJAX search box.
class Search_Series(View):
    def get(self, request):
        search_text = ''
        return redirect('scraper:tracker')

    def post(self, request):
        search_text = request.POST['search_text']
        # Empty search box.
        if search_text == '':
            series = Serie.objects.all()
        else:
            series = Serie.objects.filter(name__contains = search_text)

        return render(request, 'seriesList-Template.html', {'cont': series})

# Request to scrape tracked series and display results
class Scraper(View):
    def get(self, request):
        s = list(Serie.objects.all().values('name', 'season'))
        s = ['{0}+{1}'.format(x['name'], str(x['season'])) for x in s]
        s = [t.replace(' ', '+').replace('0', '+', 1) \
            if not t.endswith('0') else t.replace(' ', '+') for t in s]

        s = [t.replace('+1', '') if t.endswith('+1') else t for t in s]
        cont = generate_content_dictionary(s)
        # Update database entries or create new ones.
        for k, v in cont.items():
            try:
                t = Serie.objects.get(name = v["name"])
                t.episode_link = v["episode_link"]
                t.episode_num = v["episode_num"]
                t.season = v["season"]
                t.save()
            except Serie.DoesNotExist:
                tmp = Serie(name = v["name"], episode_link = v["episode_link"],
                            episode_num = v["episode_num"], season = v["season"])
                tmp.save()

        return redirect('scraper:tracker')


class Latest_Movies(View):
    def get(self, request):
        return render(request, 'latest-movies.html')

##################################################
################ Scraping Logic ##################
##################################################

def get_last_ep(series_name):
    #prettify name
    season = '1'
    name = series_name
    if '+' in series_name:
        name, season = series_name.rsplit('+', 1)
    name = name.capitalize()
    if '+' in name:
        name = name.replace('+', ' ')
    #Scrape series url (For season)
    payload = {'keyword': series_name}
    r = requests.get('{0}/filter?sort=type%5B%5D%3Dseries&type%5B%5D=series'.format(BASE_URL), params = payload)
    soup = BeautifulSoup(r.text, 'html.parser')
    result = soup.find("a", class_ = "poster")
    result = result.get('href')
    #Scrape last episode
    r2 = requests.get('{0}{1}'.format(BASE_URL, result))
    soup2 = BeautifulSoup(r2.text, 'html.parser')
    episodes = soup2.select("ul.episodes.range.active")[0]
    last_episode_link = episodes.find_all("a")[-1].get('href')
    last_episode_num = episodes.find_all("a")[-1].text
    time.sleep(5)
    return {"name": name, "episode_num": last_episode_num,
            "episode_link": '{0}{1}'.format(BASE_URL,last_episode_link),
            "season": season,
           }

# Generate Json-Like response dict for the templates.
def generate_content_dictionary(series):
    content = {}
    for s in series:
        tmp = get_last_ep(s)
        content[tmp['name']] = tmp
    return content

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equi="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0 maximum-scale=1.0">
  <meta name="description" content="">
  <title>{% block title %} {% endblock %}</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css'  %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/pi.css' %}" type="text/css" />
</head>
<body>
  <!-- Navigation Bar  -->
  <div class="navbar-wrapper">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
            <span class="sr-only"> Toggle Navigation </span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div> <!-- /navbar-header  -->
        
        <div id ="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-left">
            <!-- Add this link to the actual "tracker" page. -->
            <li><a href="{% url 'scraper:add_series' %}">Add Series</a></li>
            <li><!-- Confirmation Modal for scraping --> 
                <!-- Add this button somewhere else. --> 
              <a class="button-pointer" type="button" data-toggle="modal" data-target="#RefreshAllModal">
                Refresh All
              </a>  
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'scraper:index' %}">Home</a></li>
            <li><a href="{% url 'scraper:tracker'%}">Tracker</a></li>
            <li><a href="{% url 'scraper:latest_movies' %}">Latest Movies</a></li>
          </ul>
          <!-- Only display search box if in /tracker  -->
          {% url 'scraper:tracker' as tracker_url %}
          {% if request.get_full_path == tracker_url %}
          <!-- Search Box -->
          <div class="navbar-form navbar-center">
            <div class="form-group" style="display: inline;">
              {% csrf_token %}
              <div class="btn-group">
                <input type="search" id="search-series"  class="form-control" placeholder="Search series">
                <span id="search-series-clean" style="color: red;" class="glyphicon glyphicon-remove-circle"></span>
              </div>
            </div>
          </div>
          {% endif %}
          <!-- /End Searchbox  -->
        </div> <!-- /navbar  --> 
      </div> <!-- /container-fluid  -->
    </nav>
  </div> <!-- /navbar-wrapper  -->
  <!--Modal -->
  <div class="modal fade" id="RefreshAllModal" tabindex="-1" role="dialog"
    aria-labelledby="ScrapeModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="ScrapeModalLabel">
            Refresh All Confirmation
          </h4>
        </div>
        <div class"modal-body">
          <p style="font-size: 20px;">Refresh all tracked series?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <a type="button" class="btn btn-primary" href="{% url 'scraper:scrape' %}">Confirm</a>
        </div>
      </div>
    </div>  
  </div><!-- /Modal -->
  {% block body %}
  {% endblock %}
  <script src="{% static 'js/vendor/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %} Index {% endblock %}
{% block body %}
{% endblock %}

templates/latest-movies.html
{% extends 'base.html' %}

{% block body %}
<h1>Latest Movies</h1>
{% endblock %}

templates/scrape.html
{% extends 'base.html' %}
{% block title %} Fmovies Checker {% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="row">
    {% for k, v in cont.items %}
      <div class="col-md-4 col-xs-12">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h2 class="panel-title">{{ v.name }}</h2>
          </div>
          <div class="panel-body">
            <h4>Season: {{ v.season }}</h4>
            <h4>Last episode: {{ v.episode_num }}</h4>
            <h4>Link: <a href="{{ v.episode_link }}">{{ v.episode_link }}</a></h4>
          </div>
        </div><!-- /panel -->
      </div>
    {% endfor %}
  </div> <!-- /row -->
</div> <!-- /container-fluid -->
{% endblock %}

templates/scraper/serie_form.html
{% extends 'base.html' %}
{% block title %} Add Series {% endblock %}

{% block body %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
  </form>
{% endblock %}

templates/seriesList-Template.html
<div class="container-fluid" id="series-data">
  <div class="row">
    {% for c in cont %}
      <div class="col-md-4 col-xs-12">
        <div class="panel panel-primary">
          <div class="panel-heading clearfix">
            <h2 class="panel-title pull-left">{{ c.name.capitalize }}</h2>
            <div class="panel-buttons pull-right">
              <button type="button" class="btn btn-default" aria-label="Right Align"
                      data-toggle="modal" data-target="#serie-Refresh{{ c.id }}">
                <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
              </button>
              <button type="button" class="btn btn-default" aria-label="Right Align"
                      data-toggle="modal" data-target="#serie-Delete{{ c.id }}">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
              </button>

              <!-- Refresh Serie Modal -->
              <div class="modal fade" role="dialog" id="serie-Refresh{{ c.id }}">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Confirm Update</h4>
                    </div>
                    <div class="modal-body">
                      <p>Update {{ c.name }}?</p>
                    </div>
                    <div class="modal-footer">
                      <form action="{% url 'scraper:update_series' c.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="serie_id" value="{{ c.id }}" />
                        <button type="submit" class="btn btn-primary">Update</button>
                        <button type="button" class="btn btn-default" 
                                data-dismiss="modal">Cancel
                        </button>
                      </form>
                    </div>
                  </div><!-- /Modal Content  -->
                </div>
              </div>
              <!-- /Refresh Serie Modal  -->

              <!-- Delete Serie Modal -->
              <div class="modal fade" role="dialog" id="serie-Delete{{ c.id }}">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title" style="color: #000000;">Confirm Delete</h4>
                    </div>
                    <div class="modal-body">
                      <p style="font-size: 20px; color: #000000;">Are you sure you want to delete {{ c.name }}?</p>
                    </div>
                    <div class="modal-footer">
                      <form action="{% url 'scraper:remove_series' c.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="serie_id" value="{{ c.id }}" />
                        <button type="submit" class="btn btn-primary">Delete</button>
                        <button type="button" class="btn btn-default" 
                                data-dismiss="modal">Cancel
                        </button>
                      </form>
                    </div>
                  </div><!-- /Modal Content  -->
                </div>
              </div>
              <!-- /Delete Modal  -->

            </div><!-- /Panel Buttons -->
          </div><!--/Panel-Heading -->
          <div class="panel-body">
            <h4>Season: {{ c.season }}</h4>
            <h4>Last episode: {{ c.episode_num }}</h4>
            <h4>Link: <a href="{{ c.episode_link }}" target="_blank">{{ c.episode_link }}</a></h4>
            <h4>Last Updated: {{ c.last_updated }}</h4>
          </div>
        </div><!-- /panel -->
      </div>
    {% endfor %}
  </div> <!-- /row -->
</div> <!-- /container-fluid -->

templates/tracker.html
{% extends 'base.html' %}
{% block title %} Tracker {% endblock %}

{% block body %}
<div id="series-data"></div>
{% endblock %}